name: Daily NFL Data Collection

on:
  schedule:
    # Run daily at 9 AM UTC (4 AM EST / 1 AM PST)
    - cron: '0 9 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Run data collector
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          HEADLESS: true
        run: |
          python scripts/run_daily.py
      
      - name: Commit and push data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update data: $(date +'%Y-%m-%d %H:%M')" && git push)
      
      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nfl-data
          path: |
            data/weekly/*.json
            data/alerts/*.json
          retention-days: 7